version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8000
    volumes:
      - .:/app
